apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziyotek-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ziyotek-app-deployment
      namespace: burhan
  template:
    metadata:
      labels:
        app: ziyotek-app-deployment
        env: demo
    spec:
      containers:
      - name: ziyotek-app-deployment
        image: bhht91/devops14-docker:v5
        ports:
        - containerPort: 80
