apiVersion: v1
kind: Pod
metadata:
  name: myapp-secret
  labels:
    ziyotek: devops-secret
    environment: production
    image: private
spec:
  containers:
    - name: myapp-secret
      image: bhht91/my_demo_repo:v1
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: imagesec      