apiVersion: v1
kind: ReplicationController
metadata:
  name: ziyotek-app-rc
spec:
  replicas: 3
  selector:
    app: ziyotek-app-rc
  template:
    metadata:
      name: ziyotek-app-rc
      labels:
        app: ziyotek-app-rc
    spec:
      containers:
        - name: ziyotek-app-rc
          image: bhht91/devops14-docker:v5
          ports:
            - containerPort: 80
