apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    ziyotek: devops
    environment: production
    image: nginx
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
    - secretRef:
        name: secretnew