apiVersion: v1
kind: Service
metadata:
  name: my-deployment-svc
spec:
  type: NodePort
  selector: 
    app: ziyotek-app-deployment
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
  ports: 
    - port: 8081
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008